version: '3.4'

services:
  eventservice.api:
    image: ${DOCKER_REGISTRY-}eventserviceapi
    build:
      context: .
      dockerfile: src/EventService.Api/Dockerfile
  jwttokengenerator:
    image: hancoll/jwttokengeneratorapi:latest
