version: '3.4'

services:
  eventsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSting=mongodb://eventdb:27017"
    ports:
      - "80"
    depends_on:
      - eventdb

  eventdb:
    container_name: event_db
    restart: always
    ports:
      - "27017"
    volumes:
      - eventdb_data:/data/db

  jwttokengenerator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
