version: '3.4'

services:
  eventsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionSting=mongodb://eventdb:27017"
      - "ServiceEndpoints:ImagesService=http://imagesservice"
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - eventdb
      - imagesservice
      - paymentsservice
      - rabbitmq

  eventdb:
    container_name: event_db
    restart: always
    ports:
      - "27017"
    volumes:
      - eventdb_data:/data/db

  imagesservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
 
  spacesservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"

  paymentsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"

  jwttokengenerator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8081:80"

  rabbitmq:
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    
