version: '3.4'

services:
  eventsservice:
    image: ${DOCKER_REGISTRY-}eventsservice
    build:
      context: .
      dockerfile: src/EventsService/Dockerfile

  eventdb:
     image: mongo

  jwttokengenerator:
    image: hancoll/jwttokengeneratorapi:latest

volumes:
  eventdb_data:
    
